### ISSUE TITLE
Add listener for buttons to check if they're on the first or last page when pressing directional buttons

### ISSUE THREAD

**Issue by iCodeHaven** [masterdoctor/SpigotPaginatedGUI#1]
`
        backButton.setListener(event -> {
            PaginatedGUI menu = (PaginatedGUI) event.getClickedInventory().getHolder();
            if(currentPage <= 0) {
            	event.getWhoClicked().sendMessage(ChatColor.translateAlternateColorCodes('&', "&8\u00bb &fThere are no more previous pages."));
            	return;
            }
            menu.previousPage();
            event.getWhoClicked().closeInventory();
            event.getWhoClicked().openInventory(getInventory());
        });

nextButton.setListener(event -> {
            PaginatedGUI menu = (PaginatedGUI) event.getClickedInventory().getHolder();
            if(currentPage >= getMaxPage()) {
            	event.getWhoClicked().sendMessage(ChatColor.translateAlternateColorCodes('&', "&8\u00bb &fThere are no more extra pages."));
            	return;
            }
            menu.nextPage();
            event.getWhoClicked().closeInventory();
            event.getWhoClicked().openInventory(getInventory());
        });`

You have no checks to see if they're pressing the buttons on the first or last page, I added some for myself

**Comment by masterdoctor** [comment]
Thank you

**Comment by masterdoctor** [comment]
Anyone interested customizing the pagination items and messages, please see: https://github.com/masterdoctor/SpigotPaginatedGUI/wiki/Customizing-the-pagination-items
