### ISSUE TITLE
Pagination GUI Inventory click not working when doing multiple pages.

### ISSUE THREAD

**Issue by LuckyClutch07** [masterdoctor/SpigotPaginatedGUI#11]
I have checked the code and I noticed in your method getButton(slot); doesn't check for when currentPage is more than 0 meaning multiple pages would not work correctly. I did a fix to it 

``` 
   public GUIButton getButton(int slot) {
        if (slot < 45) {
            if(currentPage > 0)
                return items.get(slot + (45 * currentPage));
            return items.get(slot);
        } else {
            return toolbarItems.get(slot - 45);
        }
    }
```

**Comment by LuckyClutch07** [comment]
@masterdoctor also perfected the refreshInventory method:

```
public void refreshInventory(HumanEntity holder) {
        Inventory items = getInventory();
        holder.getOpenInventory().getTopInventory().setContents(items.getContents());
    }
```
This will truly refresh the inventory and not open a new one 👍

**Comment by masterdoctor** [comment]
This has been incorporated into the rewrite, [SpiGUI](https://github.com/SamJakob/SpiGUI).
