### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Pixcled** [masterdoctor/SpigotPaginatedGUI#12]
# SpigotPaginatedGUI Issue Report ##

**API Version:** `1.13`  
**Spigot Version:** `1.13.2`  
**Java Version:** 8

### Expected Behaviour
> Should open the GUI

### Actual Behaviour
> Gives error about ArrayIndexOutOfBoundsException: 45

**Comment by masterdoctor** [comment]
Please use [SpiGUI](https://github.com/SamJakob/SpiGUI) which will not have this issue.
