### ISSUE TITLE
Throws error on menu.setButton(int, button)

### ISSUE THREAD

**Issue by iCodeHaven** [masterdoctor/SpigotPaginatedGUI#2]
This is an absolutely great API, I understand that it's new, however here's another issue for you to fix
https://hastebin.com/uhahiwugoc.vbs

**Comment by masterdoctor** [comment]
Thanks, again. I'll take a look
<3

**Comment by masterdoctor** [comment]
Fixed: https://github.com/masterdoctor/SpigotPaginatedGUI/commit/a9f0acb56ef9b2e327eb6edcd9c6516596d29138
