### ISSUE TITLE
Menu name

### ISSUE THREAD

**Issue by LaxWasHere** [masterdoctor/SpigotPaginatedGUI#5]
Hi, I was wondering if you could add a method to set the menu name. 

I added this in my own repo but i'd rather you implement it on your own way.

PaginatedGUI.java
```
    public void setMenuName(String name) {
        this.name = ChatColor.translateAlternateColorCodes('&', name);
    }
```

And on my listener class, I refreshed the inventory with this.
```
                button.setListener(event -> { 
                event.setCancelled(true);
                menu.setMenuName("&4This is a test");
                event.getWhoClicked().openInventory(menu.getInventory());
                });
```

Thanks! 😸

**Comment by masterdoctor** [comment]
Solved with https://github.com/masterdoctor/SpigotPaginatedGUI/commit/e39db79a38df8adea659cad3abe96701cbaee9b0
