### ISSUE TITLE
Not setting names?

### ISSUE THREAD

**Issue by LaxWasHere** [masterdoctor/SpigotPaginatedGUI#6]
We can pass names to the constructor, we can also use the setName method but it never actually sets the name of the inventory.

Simple fix would be to add the name variable as the third argument on [createInventory](https://github.com/masterdoctor/SpigotPaginatedGUI/blob/0a7e4dd1284d73f152394876e6cef41ff21a2895/src/main/java/com/cloutteam/samjakob/gui/types/PaginatedGUI.java#L289).

:3

**Comment by masterdoctor** [comment]
Have you tried reopening the inventory manually - I may have forgotten to implement that.

**Comment by masterdoctor** [comment]
Also, I have yet to update the Maven release - I've been getting a little behind due to exams.
