### ISSUE TITLE
ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by LaxWasHere** [masterdoctor/SpigotPaginatedGUI#8]
Hey, I'm getting [ArrayIndexOutOfBounds](https://gist.github.com/anonymous/c5bd060a20fd09d078ceb30554b14ec4). Seems to have fixed it by setting the inventory size to 54 no matter what.

**Comment by masterdoctor** [comment]
I haven't implemented the changes necessary to accommodate other inventory sizes.

**Comment by LaxWasHere** [comment]
Yes, I'm just having errors from the master branch which I fixed by changing 45 to 54 [here](https://github.com/masterdoctor/SpigotPaginatedGUI/blob/master/src/main/java/com/cloutteam/samjakob/gui/types/PaginatedGUI.java#L289)

I'm not making any changes on the inventory size.

**Comment by masterdoctor** [comment]
If you revert your change, can you tell me what happens with the following:

- 0 additional pages (just 1 page overall)
- 1 additional page
- 2 additional pages

**Comment by masterdoctor** [comment]
The rewrite, [SpiGUI](https://github.com/SamJakob/SpiGUI) now supports inventories of customize-able size.
